In [1]:
import math as m

print(m.ceil(13.89));
print(m.ceil(4.5));

print(m.ceil(300.16));
print(m.ceil(300.99));

a=5.2
b=-25

print("Copysign of 5.2 and -25 is:",end=" ");
print(m.copysign(a,b));

print(m.fabs(-3.4));

print(m.factorial(3));

print(m.fmod(4,3));

print(m.frexp(8));  #4 is exponential value

#print(sum([.1,.1,.1,.1,.1,.1,.1,.1,.1,.1])); output is:- 0.99999999999999999
print(m.fsum([.1,.1,.1,.1,.1,.1,.1,.1,.1,.1]));

print(m.isfinite(200));
print(m.isfinite(m.inf));
print(m.isfinite(-m.inf));
print(m.isfinite(m.nan));

#isinf
print(m.isinf(200));

#isnan
print(m.isnan(200));
print(m.isnan(-45.30));
print(m.isnan(float("nan")));
print(m.isnan(float("inf")));
print(m.isnan(float("-nan")));
print(m.isnan(m.nan));

#ldexp
print(m.ldexp(2,5));  #x 8(2 ^ i)

print(m.modf(9.5));

#truncate
print(m.trunc(-5.2));

#exp
print(m.exp(4));    # E ^ xX is the base of natural system

print(m.expm1(4));    

print(m.log(4,2));

#hypot
print(m.hypot(4,3));

#gamma
print(m.gamma(6));

print(m.e);
print(m.nan);
print(m.pi);

print(m.gcd(12,36));

import math as m

print(m.ceil(13.89));
print(m.ceil(4.5));

print(m.ceil(300.16));
print(m.ceil(300.99));

a=5.2
b=-25

print("Copysign of 5.2 and -25 is:",end=" ");
print(m.copysign(a,b));

print(m.fabs(-3.4));

print(m.factorial(3));

print(m.fmod(4,3));

print(m.frexp(8));  #4 is exponential value

#print(sum([.1,.1,.1,.1,.1,.1,.1,.1,.1,.1])); output is:- 0.99999999999999999
print(m.fsum([.1,.1,.1,.1,.1,.1,.1,.1,.1,.1]));

print(m.isfinite(200));
print(m.isfinite(m.inf));
print(m.isfinite(-m.inf));
print(m.isfinite(m.nan));

#isinf
print(m.isinf(200));

#isnan
print(m.isnan(200));
print(m.isnan(-45.30));
print(m.isnan(float("nan")));
print(m.isnan(float("inf")));
print(m.isnan(float("-nan")));
print(m.isnan(m.nan));

#ldexp
print(m.ldexp(2,5));  #x 8(2 ^ i)

print(m.modf(9.5));

#truncate
print(m.trunc(-5.2));

#exp
print(m.exp(4));    # E ^ xX is the base of natural system

print(m.expm1(4));    

print(m.log(4,2));

#hypot
print(m.hypot(4,3));

#gamma
print(m.gamma(6));

print(m.e);
print(m.nan);
print(m.pi);

print(m.gcd(12,36));




import numpy as np


a=np.array([1,2,3,4])
print(a)

b=np.array([1,2,3,4],dtype=np.float32)
print(b)

c=np.array([1,2.0,3,4,"hello",4])
print(c)

c=np.array([1,2.0,3,4,"hello",4])
print(c.ndim)

d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d)

a=np.ones(5)
print(a)

a=np.random.rand(3,3)
print(a)

np.random.randint(7,size=(3,3))

np.full((3,3),1)

np.eye(3,k=0)

np.eye(3,k=1)

np.eye(3,k=-1)

np.eye(3,k=2)

np.arange(10)

a=np.array([[1,2,3],[4,5,6]])
a.shape

a.size

b=np.array([1,2,3,4])
c=np.reshape(b,(2,2))
print(c)


a=np.array([[1,2,3],[4,5,6]])#convert row and column
print(a)
np.transpose(a)

#Slicing numpy = number operation

l=np.array([1,2,3,4,5,6,7,8,9])
print(l[1:4:2])

#Slicing

l=np.array([1,2,3,4,5,6,7,8,9])
print(l[1:9:3])
print(l[::-1])
print(l[:1:-1])
print(l[-1])
print(l[-1:])
print(l[9::-2])

import scipy

#pip install scipy

import scipy

#determinent of matrix |A|
d=np.array([[2,1,3],[1,2,3],[3,3,20]])
print(d)
from scipy import linalg
linalg.det(d)

eigen_values,eigen_vectors = linalg.eig(d)
print(eigen_values)
print(eigen_vectors)

scipy.linalg.inv(d)


14
5
301
301
Copysign of 5.2 and -25 is: -5.2
3.4
6
1.0
(0.5, 4)
1.0
True
False
False
False
False
False
False
True
False
True
True
64.0
(0.5, 9.0)
-5
54.598150033144236
53.598150033144236
2.0
5.0
120.0
2.718281828459045
nan
3.141592653589793
12
14
5
301
301
Copysign of 5.2 and -25 is: -5.2
3.4
6
1.0
(0.5, 4)
1.0
True
False
False
False
False
False
False
True
False
True
True
64.0
(0.5, 9.0)
-5
54.598150033144236
53.598150033144236
2.0
5.0
120.0
2.718281828459045
nan
3.141592653589793
12
[1 2 3 4]
[1. 2. 3. 4.]
['1' '2.0' '3' '4' 'hello' '4']
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1. 1. 1. 1. 1.]
[[0.36580923 0.41488878 0.50680006]
 [0.06668263 0.44169282 0.37225352]
 [0.27845981 0.30543475 0.15024631]]
[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]
[2 4]
[2 5 8]
[9 8 7 6 5 4 3 2 1]
[9 8 7 6 5 4 3]
9
[9]
[9 7 5 3 1]
[[ 2  1  3]
 [ 1  2  3]
 [ 3  3 20]]
[21.+0.j  1.+0.j  2.+0.j]
[[-1.62221421e-01 -7.07106781e-01 -6.88247202e-01]
 [-1.62221421e-01  7.07106781e-01 -6.88247202e-01]
 [-9.73328527e-01 -1.67707020e-

array([[ 0.73809524, -0.26190476, -0.07142857],
       [-0.26190476,  0.73809524, -0.07142857],
       [-0.07142857, -0.07142857,  0.07142857]])