In [1]:
import math as m

print(m.ceil(13.89));
print(m.ceil(4.5));

print(m.ceil(300.16));
print(m.ceil(300.99));

a=5.2
b=-25

print("Copysign of 5.2 and -25 is:",end=" ");
print(m.copysign(a,b));

print(m.fabs(-3.4));

print(m.factorial(3));

print(m.fmod(4,3));

print(m.frexp(8));  #4 is exponential value

#print(sum([.1,.1,.1,.1,.1,.1,.1,.1,.1,.1])); output is:- 0.99999999999999999
print(m.fsum([.1,.1,.1,.1,.1,.1,.1,.1,.1,.1]));

print(m.isfinite(200));
print(m.isfinite(m.inf));
print(m.isfinite(-m.inf));
print(m.isfinite(m.nan));

#isinf
print(m.isinf(200));

#isnan
print(m.isnan(200));
print(m.isnan(-45.30));
print(m.isnan(float("nan")));
print(m.isnan(float("inf")));
print(m.isnan(float("-nan")));
print(m.isnan(m.nan));

#ldexp
print(m.ldexp(2,5));  #x 8(2 ^ i)

print(m.modf(9.5));

#truncate
print(m.trunc(-5.2));

#exp
print(m.exp(4));    # E ^ xX is the base of natural system

print(m.expm1(4));    

print(m.log(4,2));

#hypot
print(m.hypot(4,3));

#gamma
print(m.gamma(6));

print(m.e);
print(m.nan);
print(m.pi);

print(m.gcd(12,36));

import numpy as np

a=np.array([1,2,3,4])
print(a)

b=np.array([1,2,3,4],dtype=np.float32)
print(b)

c=np.array([1,2.0,3,4,"hello",4])
print(c)

c=np.array([1,2.0,3,4,"hello",4])
print(c.ndim)

d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d)

a=np.ones(5)
print(a)

a=np.random.rand(3,3)
print(a)

np.random.randint(7,size=(3,3))

np.full((3,3),1)

np.eye(3,k=0)

np.eye(3,k=1)

np.eye(3,k=-1)

np.eye(3,k=2)

np.arange(10)

a=np.array([[1,2,3],[4,5,6]])
a.shape

a.size

b=np.array([1,2,3,4])
c=np.reshape(b,(2,2))
print(c)


a=np.array([[1,2,3],[4,5,6]])#convert row and column
print(a)
np.transpose(a)

#Slicing numpy = number operation

l=np.array([1,2,3,4,5,6,7,8,9])
print(l[1:4:2])

#Slicing

l=np.array([1,2,3,4,5,6,7,8,9])
print(l[1:9:3])
print(l[::-1])
print(l[:1:-1])
print(l[-1])
print(l[-1:])
print(l[9::-2])

import scipy

#pip install scipy

import scipy

#determinent of matrix |A|
d=np.array([[2,1,3],[1,2,3],[3,3,20]])
print(d)
from scipy import linalg
linalg.det(d)

eigen_values,eigen_vectors = linalg.eig(d)
print(eigen_values)
print(eigen_vectors)

scipy.linalg.inv(d)


14
5
301
301
Copysign of 5.2 and -25 is: -5.2
3.4
6
1.0
(0.5, 4)
1.0
True
False
False
False
False
False
False
True
False
True
True
64.0
(0.5, 9.0)
-5
54.598150033144236
53.598150033144236
2.0
5.0
120.0
2.718281828459045
nan
3.141592653589793
12


[1 2 3 4]
[1. 2. 3. 4.]
['1' '2.0' '3' '4' 'hello' '4']
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1. 1. 1. 1. 1.]
[[0.68641415 0.1097333  0.61559467]
 [0.06958853 0.75570364 0.92561064]
 [0.50287581 0.62902566 0.11261727]]
[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]
[2 4]
[2 5 8]
[9 8 7 6 5 4 3 2 1]
[9 8 7 6 5 4 3]
9
[9]
[9 7 5 3 1]
[[ 2  1  3]
 [ 1  2  3]
 [ 3  3 20]]
[21.+0.j  1.+0.j  2.+0.j]
[[-1.62221421e-01 -7.07106781e-01 -6.88247202e-01]
 [-1.62221421e-01  7.07106781e-01 -6.88247202e-01]
 [-9.73328527e-01 -1.67707020e-16  2.29415734e-01]]


array([[ 0.73809524, -0.26190476, -0.07142857],
       [-0.26190476,  0.73809524, -0.07142857],
       [-0.07142857, -0.07142857,  0.07142857]])

In [2]:

import statistics

li = [1, 2, 3, 3, 4, 4, 2, 2, 1]

# using mean() to calculate average of list elements
print ("The average of list values is : ",end="")
print (statistics.mean(li))

# using mode() to print maximum occurring of list elements
print ("The maximum occurring element is : ",end="")
print (statistics.mode(li))

# using median() to print median of list elements
print ("The median of list element is : ",end="")
print (statistics.median(li))
  
# using median_low() to print low median of list elements
print ("The lower median of list element is : ",end="")
print (statistics.median_low(li))
  
# using median_high() to print high median of list elements
print ("The higher median of list element is : ",end="")
print (statistics.median_high(li))

# using median_grouped() to calculate 50th percentile
print ("The 50th percentile of data is : ",end="")
print (statistics.median_grouped(li))

# using median_grouped() to calculate 50th percentile
print ("The harmonic mean is : ",end="")
print (statistics.harmonic_mean(li))

The average of list values is : 2.4444444444444446
The maximum occurring element is : 2
The median of list element is : 2
The lower median of list element is : 2
The higher median of list element is : 2
The 50th percentile of data is : 2.3333333333333335
The harmonic mean is : 1.9285714285714286


In [3]:
import statistics

# initializing list
li = [1.5, 2.5, 2.5, 3.5, 3.5, 3.5]

# using variance to calculate variance of data
print ("The variance of data is : ",end="")
print (statistics.variance(li))

# using pvariance to calculate population variance of data
print ("The population variance of data is : ",end="")
print (statistics.pvariance(li))

# using stdev to calculate standard deviation of data
print ("The standard deviation of data is : ",end="")
print (statistics.stdev(li))
  
# using pstdev to calculate population standard deviation of data
print ("The population standard deviation of data is : ",end="")
print (statistics.pstdev(li))


The variance of data is : 0.6666666666666666
The population variance of data is : 0.5555555555555556
The standard deviation of data is : 0.816496580927726
The population standard deviation of data is : 0.7453559924999299


In [4]:
import statistics 
li=[7,11,11,15,22,20,28]

print(statistics.median(li))
print(statistics.mode(li))
print(statistics.mean(li))
print(statistics.median_low(li))
print(statistics.median_high(li))
print(statistics.median_grouped(li))
print(statistics.harmonic_mean(li))

15
11
16.285714285714285
15
15
15.0
13.396851698425849


In [5]:
import pandas as pd
import statistics
import seaborn as sns


In [6]:
df = pd.read_csv("C:\\Users\\HP\\Downloads\\purchase.csv")
df.head()


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [10]:
import pandas as pd
from statistics import mode

# Assuming 'data' is your DataFrame
data = {
    'User ID': [15624510, 15810944, 15668575, 15603246, 15804002],
    'Gender': ['Male', 'Male', 'Female', 'Female', 'Male'],
    'Age': [19, 35, 26, 27, 19],
    'EstimatedSalary': [19000, 20000, 43000, 57000, 76000],
    'Purchased': [0, 0, 0, 0, 0]
}
df = pd.DataFrame(data)

# Calculate mean
gender_mean = df['Gender'].value_counts().mean()

# Calculate mode
gender_mode = mode(df['Gender'])

# Calculate median
gender_median = df['Gender'].value_counts().median()

print(f"Mean: {gender_mean}")
print(f"Mode: {gender_mode}")
print(f"Median: {gender_median}")

Mean: 2.5
Mode: Male
Median: 2.5


In [7]:
df.shape

(400, 5)

In [11]:
Age1=df['Age']
type(Age1)


pandas.core.series.Series

In [12]:
statistics.mean(Age1)


25.2

In [ ]:
statistics.median(Age1)

37.0

In [ ]:
statistics.mode(Age1)

35

In [ ]:
statistics.variance(Age1)

109.89070175438596

In [ ]:
Age1.describe() #quality range

count    400.000000
mean      37.655000
std       10.482877
min       18.000000
25%       29.750000
50%       37.000000
75%       46.000000
max       60.000000
Name: Age, dtype: float64

In [ ]:
max1=max(Age1)
print(max1)

60


In [ ]:
min1=min(Age1)
print(min1)

18


In [ ]:
range=max1-min1
print(range)

42


In [ ]:
statistics.stdev(Age1)/statistics.mean(Age1)*100   #coefficient of variation

27.839268615875483

In [ ]:
statistics.mode(Age1)